#!/bin/bash

. kcp_ss_lib

start_container(){
  CONTAINER_ID=$(get_docker_container_id)
  echo "Current container: $CONTAINER_ID"

  IMAGE_NAME=$(get_docker_image_name $CONTAINER_ID)
  echo "Current image: $IMAGE_NAME"

  INTERFACE=${INTERFACE:-$(get_default_network_interface)}
  echo "Network interface: $INTERFACE"

  HOST=${HOST:-$(get_default_network_ip)}
  echo "Host name: $HOST"

  # SS_PORT=${SS_PORT:-$(find_available_port tcp 5000 20000)}
  # echo "Exported Shadowsocks port: $SS_PORT"

  # KCPTUN_PORT=${KCPTUN_PORT:-$(find_available_port udp 5000 20000)}
  # echo "Exported KCPTUN port: $KCPTUN_PORT"

  # if [ $SS_PORT -eq $KCPTUN_PORT ]; then
	# echo "ERROR: SS_PORT $SS_PORT is equal to KCPTUN_PORT $KCPTUN_PORT." >&2
	# exit 1
  # fi

  # PASSWORD=${PASSWORD:-$(pwgen 8 1)}
  # echo "Password: $PASSWORD"

  # SS_METHOD=${SS_METHOD:-aes-256-cfb}
  # echo "Shadowsocks method: $SS_METHOD"

  # KCPTUN_CRYPT=${KCPTUN_CRYPT:-aes}
  # echo "KCPTUN crypt: $KCPTUN_CRYPT"

  # KCPTUN_MODE=${KCPTUN_MODE:-normal}
  # echo "KCPTUN mode: $KCPTUN_MODE"

  setup_bootstrap_envs

  echo

  COMMAND_LINE=$(generate_dood_command \
    $IMAGE_NAME $HOST $SS_PORT $PASSWORD $KCPTUN_PORT $PASSWORD $SS_METHOD $KCPTUN_CRYPT $KCPTUN_MODE)
  echo $COMMAND_LINE

  echo

  WORKER_CONTAINER_ID=$($COMMAND_LINE)
  echo "Worker container: $WORKER_CONTAINER_ID"
  WORKER_CONTAINER_NAME=$(docker inspect -f '{{.Name}}' $WORKER_CONTAINER_ID|tail -c +2)
  echo "Worker container name: $WORKER_CONTAINER_NAME"

  echo
  echo "----"
  echo

  docker exec -i $WORKER_CONTAINER_ID show
}

# test_all

start_container
