#!/bin/bash

. kcp_ss_lib

echo "Shadowsocks link: $SS_LINK"
echo
echo "QR code: $(qr_link $SS_LINK)"
echo
echo "----"
echo
echo "KCPTUN SS link (for Android client only): $KCPTUN_SS_LINK"
echo
echo "QR code: $(qr_link $KCPTUN_SS_LINK)"
echo
