name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yaleh/kcp-shadowsocks-server:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push yaleh/kcp-shadowsocks-server:${{steps.vars.outputs.tag}}
    
