name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(date +%s)
    - name: Build branch name
      shell: bash
      run: |
        [[ $GITHUB_REF_NAME = "master" ]] && TAG="latest" || TAG=$GITHUB_REF_NAME
        echo "::set-output name=branch::$TAG"
      id: branch_name
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yaleh/kcp-shadowsocks-server:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push yaleh/kcp-shadowsocks-server:${{steps.vars.outputs.tag}}
    - name: Save the tagged Docker image
      run: docker save -o kcp-shadowsocks-server.${{steps.vars.outputs.tag}}.tar.gz yaleh/kcp-shadowsocks-server:${{steps.vars.outputs.tag}}
    - name: Upload the saved tagged Docker image
      uses: actions/upload-artifact@v2
      with:
        name: kcp-shadowsocks-server.${{steps.vars.outputs.tag}}.tar.gz
        path: kcp-shadowsocks-server.${{steps.vars.outputs.tag}}.tar.gz
    - name: Tag the image as the branch one
      run: docker tag yaleh/kcp-shadowsocks-server:${{steps.vars.outputs.tag}} yaleh/kcp-shadowsocks-server:${{steps.branch_name.outputs.branch}}
    # - name: Build the branch Docker image
    #   run: docker build . --file Dockerfile --tag yaleh/kcp-shadowsocks-server:${{steps.branch_name.outputs.branch}}
    - name: Push the tagged branch Docker image
      run: docker push yaleh/kcp-shadowsocks-server:${{steps.branch_name.outputs.branch}}
    
